/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BecomeAHostRouteImport } from './routes/become-a-host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as EventsIdCheckinRouteImport } from './routes/events.$id.checkin'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as DashboardEventsIdEditRouteImport } from './routes/dashboard.events.$id.edit'
import { Route as DashboardEventsIdCheckinRouteImport } from './routes/dashboard.events.$id.checkin'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAHostRoute = BecomeAHostRouteImport.update({
  id: '/become-a-host',
  path: '/become-a-host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsIdCheckinRoute = EventsIdCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => EventsIdRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdEditRoute = DashboardEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdCheckinRoute =
  DashboardEventsIdCheckinRouteImport.update({
    id: '/events/$id/checkin',
    path: '/events/$id/checkin',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/dashboard/events/$id/checkin': typeof DashboardEventsIdCheckinRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/dashboard/events/$id/checkin': typeof DashboardEventsIdCheckinRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/dashboard/events/$id/checkin': typeof DashboardEventsIdCheckinRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-a-host'
    | '/dashboard'
    | '/my-events'
    | '/my-tickets'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/profile'
    | '/events/$id'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/dashboard/events/$id/checkin'
    | '/dashboard/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-host'
    | '/dashboard'
    | '/my-events'
    | '/my-tickets'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/profile'
    | '/events/$id'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/dashboard/events/$id/checkin'
    | '/dashboard/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/become-a-host'
    | '/dashboard'
    | '/my-events'
    | '/my-tickets'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/profile'
    | '/events/$id'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/dashboard/events/$id/checkin'
    | '/dashboard/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeAHostRoute: typeof BecomeAHostRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  MyEventsRoute: typeof MyEventsRoute
  MyTicketsRoute: typeof MyTicketsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EventsIdRoute: typeof EventsIdRouteWithChildren
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-host': {
      id: '/become-a-host'
      path: '/become-a-host'
      fullPath: '/become-a-host'
      preLoaderRoute: typeof BecomeAHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$id/checkin': {
      id: '/events/$id/checkin'
      path: '/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof EventsIdCheckinRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id/edit': {
      id: '/dashboard/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/dashboard/events/$id/edit'
      preLoaderRoute: typeof DashboardEventsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id/checkin': {
      id: '/dashboard/events/$id/checkin'
      path: '/events/$id/checkin'
      fullPath: '/dashboard/events/$id/checkin'
      preLoaderRoute: typeof DashboardEventsIdCheckinRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardEventsIdCheckinRoute: typeof DashboardEventsIdCheckinRoute
  DashboardEventsIdEditRoute: typeof DashboardEventsIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardEventsIdCheckinRoute: DashboardEventsIdCheckinRoute,
  DashboardEventsIdEditRoute: DashboardEventsIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsIdRouteChildren {
  EventsIdCheckinRoute: typeof EventsIdCheckinRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdCheckinRoute: EventsIdCheckinRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeAHostRoute: BecomeAHostRoute,
  DashboardRoute: DashboardRouteWithChildren,
  MyEventsRoute: MyEventsRoute,
  MyTicketsRoute: MyTicketsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EventsIdRoute: EventsIdRouteWithChildren,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
